### ISSUE TITLE
`codeblock-pict` treats 'comment the same as 'other

### ISSUE THREAD

**Issue by florence** [racket/pict#13]
Example:

`codeblock-pict` renders: 
![screen shot 2016-01-15 at 3 16 20 pm](https://cloud.githubusercontent.com/assets/1413610/12365567/3743eca0-bb9b-11e5-9248-0ffd208bb1fa.png)

Whereas DrRacket renders: 
![screen shot 2016-01-15 at 3 17 41 pm](https://cloud.githubusercontent.com/assets/1413610/12365569/3967b5de-bb9b-11e5-8bc3-80790d7e0274.png)

Where the `//` line lexes as `'comment` and `in` and `to` lex as `'other`

**Comment by stamourv** [comment]
That's just an artifact of the fact that `pict/code` uses the same color for `current-base-color` (used for `'other`) and `current-comment-color`. Luckily, you can change those in your own code.

![screen shot 2016-01-27 at 4 26 04 pm](https://cloud.githubusercontent.com/assets/854429/12630581/c0f07d26-c512-11e5-9147-46b75db9e2f6.png)
