### ISSUE TITLE
The fast-edges animation is the same as the fast-middle animation

### ISSUE THREAD

**Issue by LeifAndersen** [racket/pict#17]
At least in the docs, the image used for `fast-edges` and `fast-middle` is identical.

(This only appears to be in the docs for master, not the stable builds).

https://www.cs.utah.edu/plt/snapshots/current/doc/pict/Animation_Helpers.html?q=fast-edge#%28def._%28%28lib._pict%2Fmain..rkt%29._fast-edges%29%29

**Comment by mflatt** [comment]
It looks to me like `fast-edges` is broken (and just a more complex version of `fast-middle`), so I'll fix that.

@asumu Cool docs.
