### ISSUE TITLE
Type 3 fonts in Racket 7.0 pdfs

### ISSUE THREAD

**Issue by bennn** [racket/pict#42]
Racket 7.0 sometimes uses Type 3 fonts when rendering picts to pdf. The same picts don't use Type 3 fonts in Racket v6.12. This is bad because the ~sigplan conference publishing team~ ACM DL will not accept pdfs with Type 3 fonts.

The difference is because v7.0 uses different pango and cairo dylibs --- but I don't know whether those dylibs or racket's use of them is the problem.

Example program:

```
#lang racket/base
(require pict file/convertible)

(with-output-to-file "pict.pdf" #:exists 'replace
  (λ () (display (convert (text "Hello World") 'pdf-bytes))))
```

To reproduce:

0. install the `poppler` library (to get the `pdffonts` command)
1. run `racket example.rkt`
2. run `pdffonts pict.pdf` and look for Type 3 fonts

Example output on Racket 6.12:

```
$ /Applications/Racket\ v6.12/bin/racket example.rkt
$ pdffonts pict.pdf
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
NGYLUJ+LucidaGrande                  CID TrueType      Identity-H       yes yes yes      5  0
```

Example output on Racket 7.0:

```
$ /Applications/Racket\ v7.0/bin/racket example.rkt
$ pdffonts pict.pdf
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
WIOEMU+LucidaGrande                  TrueType          WinAnsi          yes yes yes      5  0
[none]                               Type 3            Custom           yes no  yes      6  0
```

cc and thanks for helping identify this issue: @LeifAndersen @rfindler

**Comment by bennn** [comment]
A temporary work-around is to revert to the older dylibs, e.g. on i386-macosx:

1. Download the zipfile at <https://pkgs.racket-lang.org/package/draw-i386-macosx-2>
2. Copy the dylibs buried in the zipfile to the `racket/lib` folder in your checkout of the `racket/racket` repo

**Comment by rfindler** [comment]
Turns out that the conference publishing people are not imposing the requirement; they are merely checking the requirements imposed by the ACM DL.

**Comment by LeifAndersen** [comment]
For what its worth, the following code snippet seems to not use type 3 fonts:

```
#lang scratch

(define dc (new pdf-dc%
                [interactive #f]
                [as-eps #t]
                [width 500]
                [height 500]
                [output "out.pdf"]))
(send dc start-doc "pict")
(send dc start-page)
(send dc draw-text "Hello" 0 0 #t)
(send dc end-page)
(send dc end-doc)
```

**Comment by LeifAndersen** [comment]
Also ben, you don't need to install the `poppler` library to see this bug.

**Comment by LeifAndersen** [comment]
(After talking to ben, I realize he was just using it for the `pdffonts` command, rather than Racket's poppler library.)

**Comment by mflatt** [comment]
The difference between the original example and Leif's example is that the original has a space in the string.

It took me a while to remember that I've been here before, and I found the patch that got lost in the libraries upgrade.
