### ISSUE TITLE
`lift-above-baseline` extends bounding box incorrectly (I think)

### ISSUE THREAD

**Issue by florence** [racket/pict#56]
The documentation for `lift-above-baseline` reads:

"Lifts pict relative to its baseline, extending the bounding box height if necessary."

However the bounding box is not extended if the shift is negative, and the bounding box seems to get smaller on positive lifts:

```
> (define t (text "O"))
> (pict-height (lift-above-baseline t -5))
14.1328125
> (pict-height (lift-above-baseline t (pict-height t)))
2.53125
```

However I worry that changing this function to either never extend the bounding box, or to extend it in a more expected way will be completely backwards incompatible. (For example, I know it will probably change the rendering of at least one of my papers).

So I'm thinking to fix this like so:

Have lift-above-baseline not change the bounding box by default (since shrinking the bounding box on a lift seems like nonsense to me), and add an optional flag for it to extend the bounding box on a negative or positive lift. 

Does this seem like a reasonable compromise?

**Comment by mflatt** [comment]
That sounds ok. I agree that changing the default behavior would break lots of things.

**Comment by rfindler** [comment]
Another idea is to make another function with a different name and have the docs for this one point to that one? I see that `lift` isn't taken (but maybe that name needs an especially useful function that somehow captured more stuff based on its short name).

**Comment by florence** [comment]
`drop-below-ascent` seems to have similar odd behavior:

```
> (pict-height t)
14.1328125
> (pict-height (drop-below-ascent t -5))
14.1328125
> (pict-height (drop-below-ascent t 5))
14.1328125
> (pict-height (drop-below-ascent t 15))
10.734375
```

So how about the following:

Deprecate `lift-above-descent` and `drop-below-descent`, and add a function like:

```
(lift-relative-to pict baseline [ascent #:extend-bb? bb?])
```

Where the "ascent" behaves like the minus of `drop-below-ascent`.

if `bb?` is false this function basically just moves the ascent/descent line up and down the pict, possibly moving it out of the pict. if `bb?` is true, the bounding box is extended vertically by `(+ baseline ascent)` in the appropriate manor.

**Comment by florence** [comment]
(or maybe their should be two functions, not sure...)

**Comment by rfindler** [comment]
(couldn't resist the homophone correction)

**Comment by rfindler** [comment]
What about a single function named `lift-or-drop` that accepts a pict and an amount and returns a pict whose drawing content is moved wrt to the baseline, but that keeps the same bounding box. And then has optional arguments to lift/drop wrt to other lines and to extend the bounding box. 

Are there other things that the existing lift and drop functions (are supposed to) do?

**Comment by florence** [comment]
I think thats basically what I'm proposing.

There is some stuff in the existing lift/drop to shift the other line (ascent/descent) in the case that they define the same line (though in that case i think the two functions are roughly equivalent). So ill preserve that behavior. I'll try to get a proposal pull request later today.
