### ISSUE TITLE
`shadow-frame` doesn't work with `scale`

### ISSUE THREAD

**Issue by stamourv** [racket/pict#6]

**Comment by stamourv** [comment]
See http://bugs.racket-lang.org/query/?cmd=view&pr=15140

**Comment by mflatt** [comment]
@stamourv @rmculpepper Did someone fix this? I'm unable to replicate the problem.

**Comment by stamourv** [comment]
FWIW, I can't reproduce the problem in slideshow, but I can in DrRacket.
That reminds me of an earlier pict-related bug that only happened in DrRacket, where the issue was with record-dc. [cc @rfindler]
![screen shot 2016-04-06 at 12 48 23 pm](https://cloud.githubusercontent.com/assets/854429/14326975/ed9f4d1a-fbf5-11e5-8e4b-739986f40ffa.png)

**Comment by stamourv** [comment]
For reference, the code that generated the above:
```
#lang racket
(require pict pict/shadow slideshow)(angel-wing 100 100 #t)
(scale (angel-wing 200 200 #t) 1/2)
(shadow-frame (blank 50))
(scale (shadow-frame (blank 25)) 2)
```

**Comment by mflatt** [comment]
Thanks – and, yes, a problem with `record-dc%`
