### ISSUE TITLE
`cc-find` yields different results on different racket versions (v7.7 vs v7.8)

### ISSUE THREAD

**Issue by lihebi** [racket/pict#65]
I'm getting different results for `cc-find` on different racket versions. `v7.7` seems to be correct, `v7.8` seems to be broken, where `cc-find` yields **negative** values. Here are the details.

The following script:

```racket
#lang racket

(require pict)
(define a (cc-superimpose (rectangle 30 30) (scale (text "A") 2)))
(define b (cc-superimpose (rectangle 30 30) (scale (text "B") 2)))
(define c (frame (rotate (vc-append a b) (- (/ pi 10)))))
(cc-find c a)
```

A visual run of what it does:

<img width="590" alt="Screen Shot 2021-05-25 at 4 58 20 PM" src="https://user-images.githubusercontent.com/4576201/119574506-491a0080-bd7b-11eb-9be5-8bdca39960c8.png">

I'm testing this code on different racket versions using [`racket/racket`](https://hub.docker.com/r/racket/racket) docker images:

```
docker run -it --rm -v /path/to/test.rkt:/test.rkt racket/racket:7.7-full racket /test.rkt
```

The results:

- v7.7-full:

```
28.72748095188456
19.471365063376922
```

- v7.8-full, v8.0-full, v8.1-full

```
-0.19578546302995292
10.200855232128504
```

NOTE that this result is **negative**, which does not make sense.

Actually, when I run racket-minimal (e.g. `racket/racket:8.1`) and install `pict` manually by `raco pkg install pict`, the results seem to be consistent for all the racket versions (`v7.7` through `v8.1`), BUT yet another different result:

```
0.3600829975546702
9.630592828803096
```

**Comment by mflatt** [comment]
Thanks for the report!
